-- ============================================================
-- CRM EXTRUCOL - SCHEMA DDL
-- Oracle APEX 20.1.0.00.13 Compatible
-- Run each CREATE TABLE separately in APEX SQL Workshop
-- ============================================================

PROMPT Creando tablas...

-- 01 CIUDADES
CREATE TABLE CRM_CIUDADES (
  ID            NUMBER         NOT NULL,
  DEPARTAMENTO  VARCHAR2(60)   NOT NULL,
  CIUDAD        VARCHAR2(100)  NOT NULL,
  CAPITAL       NUMBER(1)      DEFAULT 0,
  ACTIVO        NUMBER(1)      DEFAULT 1,
  CONSTRAINT CRM_CIUDADES_PK PRIMARY KEY (ID)
);

-- 02 USUARIOS
CREATE TABLE CRM_USUARIOS (
  ID            NUMBER         NOT NULL,
  NOMBRE        VARCHAR2(150)  NOT NULL,
  EMAIL         VARCHAR2(200)  NOT NULL UNIQUE,
  CONTRASENA    VARCHAR2(200),
  ROL           VARCHAR2(20)   NOT NULL CHECK (ROL IN ('ADMIN','DIRECTOR','COORDINADOR','EJECUTIVO')),
  CIUDAD_ID     NUMBER,
  TELEFONO      VARCHAR2(30),
  ACTIVO        NUMBER(1)      DEFAULT 1,
  FECHA_CREACION DATE         DEFAULT SYSDATE,
  CONSTRAINT CRM_USUARIOS_PK PRIMARY KEY (ID),
  CONSTRAINT CRM_USUARIOS_FK_CIUD FOREIGN KEY (CIUDAD_ID) REFERENCES CRM_CIUDADES(ID)
);

-- 03 CLIENTES
CREATE TABLE CRM_CLIENTES (
  ID            NUMBER         NOT NULL,
  NOMBRE        VARCHAR2(200)  NOT NULL,
  EMPRESA       VARCHAR2(200),
  SECTOR        VARCHAR2(100),
  CIUDAD_ID     NUMBER,
  EMAIL         VARCHAR2(200),
  TELEFONO      VARCHAR2(30),
  DIRECCION     VARCHAR2(300),
  ACTIVO        NUMBER(1)      DEFAULT 1,
  FECHA_CREACION DATE         DEFAULT SYSDATE,
  CONSTRAINT CRM_CLIENTES_PK PRIMARY KEY (ID),
  CONSTRAINT CRM_CLIENTES_FK_CIUD FOREIGN KEY (CIUDAD_ID) REFERENCES CRM_CIUDADES(ID)
);

-- 04 LEADS
CREATE TABLE CRM_LEADS (
  ID            NUMBER         NOT NULL,
  NOMBRE        VARCHAR2(200)  NOT NULL,
  EMPRESA       VARCHAR2(200),
  EMAIL         VARCHAR2(200),
  TELEFONO      VARCHAR2(30),
  ORIGEN        VARCHAR2(50),
  SECTOR        VARCHAR2(100),
  CIUDAD_ID     NUMBER,
  DESCRIPCION   CLOB,
  ESTADO        VARCHAR2(20)   DEFAULT 'NUEVO' CHECK (ESTADO IN ('NUEVO','CONTACTADO','CALIFICADO','CONVERTIDO','DESCARTADO')),
  EJECUTIVO_ID  NUMBER,
  ACTIVO        NUMBER(1)      DEFAULT 1,
  FECHA_CREACION DATE         DEFAULT SYSDATE,
  CONSTRAINT CRM_LEADS_PK PRIMARY KEY (ID),
  CONSTRAINT CRM_LEADS_FK_CIUD FOREIGN KEY (CIUDAD_ID) REFERENCES CRM_CIUDADES(ID),
  CONSTRAINT CRM_LEADS_FK_EJEC FOREIGN KEY (EJECUTIVO_ID) REFERENCES CRM_USUARIOS(ID)
);

-- 05 OPORTUNIDADES
CREATE TABLE CRM_OPORTUNIDADES (
  ID                NUMBER         NOT NULL,
  NOMBRE            VARCHAR2(300)  NOT NULL,
  DESCRIPCION       CLOB,
  TIPO              VARCHAR2(30)   DEFAULT 'VENTA' CHECK (TIPO IN ('COTIZACION','VENTA','ACOMPANAMIENTO','PROYECTO')),
  ESTADO            VARCHAR2(30)   DEFAULT 'PROSPECTO' CHECK (ESTADO IN ('PROSPECTO','CALIFICACION','PROPUESTA','NEGOCIACION','GANADA','PERDIDA')),
  VALOR_ESTIMADO    NUMBER(15,2) DEFAULT 0,
  FECHA_CIERRE      DATE,
  FECHA_ESTADO      DATE           DEFAULT SYSDATE,
  CLIENTE_ID        NUMBER,
  EJECUTIVO_ID     NUMBER        NOT NULL,
  MOTIVO_CIERRE     VARCHAR2(500),
  ACTIVO            NUMBER(1)      DEFAULT 1 CHECK (ACTIVO IN (0,1)),
  FECHA_CREACION    DATE           DEFAULT SYSDATE,
  FECHA_UPDATE      DATE           DEFAULT SYSDATE,
  CONSTRAINT CRM_OPORTUNIDADES_PK PRIMARY KEY (ID),
  CONSTRAINT CRM_OPORTUNIDADES_FK_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CRM_CLIENTES(ID),
  CONSTRAINT CRM_OPORTUNIDADES_FK_EJEC FOREIGN KEY (EJECUTIVO_ID) REFERENCES CRM_USUARIOS(ID)
);

-- 06 ACTIVIDADES
CREATE TABLE CRM_ACTIVIDADES (
  ID                NUMBER         NOT NULL,
  TIPO              VARCHAR2(20)   NOT NULL CHECK (TIPO IN ('LLAMADA','REUNION','VISITA','CORREO')),
  DESCRIPCION       CLOB,
  RESULTADO         CLOB,
  VIRTUAL           NUMBER(1)      DEFAULT 0 CHECK (VIRTUAL IN (0,1)),
  FECHA_ACTIVIDAD   DATE,
  FECHA_REGISTRO    DATE          DEFAULT SYSDATE,
  OPORTUNIDAD_ID    NUMBER,
  EJECUTIVO_ID      NUMBER        NOT NULL,
  LATITUD           NUMBER(10,6),
  LONGITUD          NUMBER(10,6),
  ACTIVO            NUMBER(1)     DEFAULT 1 CHECK (ACTIVO IN (0,1)),
  FECHA_CREACION    DATE          DEFAULT SYSDATE,
  FECHA_UPDATE      DATE          DEFAULT SYSDATE,
  CONSTRAINT CRM_ACTIVIDADES_PK PRIMARY KEY (ID),
  CONSTRAINT CRM_ACTIVIDADES_FK_OPOR FOREIGN KEY (OPORTUNIDAD_ID) REFERENCES CRM_OPORTUNIDADES(ID),
  CONSTRAINT CRM_ACTIVIDADES_FK_EJEC FOREIGN KEY (EJECUTIVO_ID) REFERENCES CRM_USUARIOS(ID)
);

-- 07 PROYECTOS
CREATE TABLE CRM_PROYECTOS (
  ID                NUMBER         NOT NULL,
  NOMBRE            VARCHAR2(300)  NOT NULL,
  DESCRIPCION       CLOB,
  ESTADO            VARCHAR2(20)   DEFAULT 'ACTIVO' CHECK (ESTADO IN ('ACTIVO','PAUSADO','FINALIZADO','CANCELADO')),
  OPORTUNIDAD_ID    NUMBER,
  FECHA_INICIO      DATE,
  FECHA_FIN         DATE,
  ACTIVO            NUMBER(1)      DEFAULT 1 CHECK (ACTIVO IN (0,1)),
  FECHA_CREACION    DATE          DEFAULT SYSDATE,
  FECHA_UPDATE      DATE          DEFAULT SYSDATE,
  CONSTRAINT CRM_PROYECTOS_PK PRIMARY KEY (ID),
  CONSTRAINT CRM_PROYECTOS_FK_OPOR FOREIGN KEY (OPORTUNIDAD_ID) REFERENCES CRM_OPORTUNIDADES(ID)
);

-- 08 METAS
CREATE TABLE CRM_METAS (
  ID            NUMBER         NOT NULL,
  EJECUTIVO_ID  NUMBER        NOT NULL,
  PERIODO       VARCHAR2(7)   NOT NULL,
  TIPO_META     VARCHAR2(20)  NOT NULL CHECK (TIPO_META IN ('NUMERO','VALOR')),
  META_VALOR    NUMBER(15,2) NOT NULL,
  META_ALCANZADA NUMBER(15,2) DEFAULT 0,
  ESTADO        VARCHAR2(15)  DEFAULT 'ACTIVA' CHECK (ESTADO IN ('ACTIVA','CUMPLIDA','VENCIDA')),
  ACTIVO        NUMBER(1)     DEFAULT 1 CHECK (ACTIVO IN (0,1)),
  FECHA_CREACION DATE         DEFAULT SYSDATE,
  CONSTRAINT CRM_METAS_PK PRIMARY KEY (ID),
  CONSTRAINT CRM_METAS_FK_EJEC FOREIGN KEY (EJECUTIVO_ID) REFERENCES CRM_USUARIOS(ID)
);

-- 09 ALERTAS
CREATE TABLE CRM_ALERTAS (
  ID            NUMBER         NOT NULL,
  TITULO        VARCHAR2(200)  NOT NULL,
  MENSAJE       CLOB,
  TIPO          VARCHAR2(20)   NOT NULL CHECK (TIPO IN ('INFO','AVISO','WARNING','ERROR')),
  USUARIO_ID    NUMBER         NOT NULL,
  ESTADO        VARCHAR2(15)   DEFAULT 'PENDIENTE' CHECK (ESTADO IN ('PENDIENTE','LEIDA','ELIMINADA')),
  FECHA_ALERTA  DATE           DEFAULT SYSDATE,
  ACTIVO        NUMBER(1)      DEFAULT 1 CHECK (ACTIVO IN (0,1)),
  CONSTRAINT CRM_ALERTAS_PK PRIMARY KEY (ID),
  CONSTRAINT CRM_ALERTAS_FK_USU FOREIGN KEY (USUARIO_ID) REFERENCES CRM_USUARIOS(ID)
);

-- 10 UBICACIONES (MONITOREO GPS)
CREATE TABLE CRM_UBICACIONES (
  ID            NUMBER         NOT NULL,
  USUARIO_ID    NUMBER         NOT NULL,
  LATITUD       NUMBER(10,6)  NOT NULL,
  LONGITUD      NUMBER(10,6)  NOT NULL,
  PRECISION     NUMBER(6,2),
  FECHA_REGISTRO DATE         DEFAULT SYSDATE,
  ACTIVO        NUMBER(1)      DEFAULT 1 CHECK (ACTIVO IN (0,1)),
  CONSTRAINT CRM_UBICACIONES_PK PRIMARY KEY (ID),
  CONSTRAINT CRM_UBICACIONES_FK_USU FOREIGN KEY (USUARIO_ID) REFERENCES CRM_USUARIOS(ID)
);

-- 11 REPORTES
CREATE TABLE CRM_REPORTES (
  ID            NUMBER         NOT NULL,
  TIPO          VARCHAR2(30)   NOT NULL,
  TITULO        VARCHAR2(200)  NOT NULL,
  PARAMETROS    CLOB,
  GENERADO_POR  NUMBER         NOT NULL,
  FECHA_GENERA  DATE           DEFAULT SYSDATE,
  ACTIVO        NUMBER(1)      DEFAULT 1 CHECK (ACTIVO IN (0,1)),
  CONSTRAINT CRM_REPORTES_PK PRIMARY KEY (ID),
  CONSTRAINT CRM_REPORTES_FK_USU FOREIGN KEY (GENERADO_POR) REFERENCES CRM_USUARIOS(ID)
);

PROMPT Tablas creadas. Ahora ejecutar los PACKAGE SPECS y BODIES por separado.