CREATE OR REPLACE PACKAGE CRM_CLIENTES_API AS
  PROCEDURE CLIENTES_LIST(p_result OUT SYS_REFCURSOR);
  PROCEDURE CLIENTES_GET(p_result OUT SYS_REFCURSOR, p_x01 IN NUMBER);
  PROCEDURE CLIENTES_CREATE(p_result OUT SYS_REFCURSOR, p_x01 IN VARCHAR2, p_x02 IN VARCHAR2, p_x03 IN VARCHAR2, p_x04 IN NUMBER DEFAULT NULL, p_x05 IN VARCHAR2 DEFAULT NULL, p_x06 IN VARCHAR2 DEFAULT NULL);
  PROCEDURE CLIENTES_UPDATE(p_result OUT SYS_REFCURSOR, p_x01 IN NUMBER, p_x02 IN VARCHAR2, p_x03 IN VARCHAR2, p_x04 IN VARCHAR2, p_x05 IN NUMBER DEFAULT NULL, p_x06 IN VARCHAR2 DEFAULT NULL, p_x07 IN VARCHAR2 DEFAULT NULL);
END CRM_CLIENTES_API;