CREATE OR REPLACE PACKAGE CRM_PROYECTOS_API AS
  PROCEDURE PROYECTOS_LIST(p_result OUT SYS_REFCURSOR, p_x01 IN NUMBER DEFAULT NULL);
  PROCEDURE PROYECTOS_LIST_TODAS(p_result OUT SYS_REFCURSOR);
  PROCEDURE PROYECTOS_GET(p_result OUT SYS_REFCURSOR, p_x01 IN NUMBER);
  PROCEDURE PROYECTOS_CREATE(p_result OUT SYS_REFCURSOR, p_x01 IN VARCHAR2, p_x02 IN CLOB DEFAULT NULL, p_x03 IN NUMBER DEFAULT NULL);
  PROCEDURE PROYECTOS_UPDATE(p_result OUT SYS_REFCURSOR, p_x01 IN NUMBER, p_x02 IN VARCHAR2, p_x03 IN CLOB DEFAULT NULL, p_x04 IN VARCHAR2 DEFAULT NULL, p_x05 IN NUMBER DEFAULT NULL);
  PROCEDURE PROYECTOS_ESTADO(p_result OUT SYS_REFCURSOR, p_x01 IN NUMBER, p_x02 IN VARCHAR2);
END CRM_PROYECTOS_API;