-- ============================================================
-- CRM EXTRUCOL - PROYECTOS DDL
-- Estados: ACTIVO, PAUSADO, FINALIZADO, CANCELADO
-- ============================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CRM_PROYECTOS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CRM_PROYECTOS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE SEQUENCE CRM_PROYECTOS_SEQ START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE TABLE CRM_PROYECTOS (
  ID                NUMBER         NOT NULL,
  NOMBRE            VARCHAR2(300)  NOT NULL,
  DESCRIPCION       CLOB,
  ESTADO            VARCHAR2(20)   DEFAULT 'ACTIVO' CHECK (ESTADO IN ('ACTIVO','PAUSADO','FINALIZADO','CANCELADO')),
  OPORTUNIDAD_ID    NUMBER,
  FECHA_INICIO      DATE,
  FECHA_FIN         DATE,
  ACTIVO            NUMBER(1)      DEFAULT 1 CHECK (ACTIVO IN (0,1)),
  FECHA_CREACION    DATE          DEFAULT SYSDATE,
  FECHA_UPDATE      DATE          DEFAULT SYSDATE,
  CONSTRAINT CRM_PROYECTOS_PK PRIMARY KEY (ID),
  CONSTRAINT CRM_PROYECTOS_FK_OPOR FOREIGN KEY (OPORTUNIDAD_ID) REFERENCES CRM_OPORTUNIDADES(ID)
);

CREATE INDEX CRM_PROYECTOS_OPOR_IDX  ON CRM_PROYECTOS(OPORTUNIDAD_ID);
CREATE INDEX CRM_PROYECTOS_ESTADO_IDX ON CRM_PROYECTOS(ESTADO);

CREATE OR REPLACE TRIGGER TRG_PROYECTOS_BI
BEFORE INSERT ON CRM_PROYECTOS FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN :NEW.ID := CRM_PROYECTOS_SEQ.NEXTVAL; END IF;
END TRG_PROYECTOS_BI;
/

CREATE OR REPLACE TRIGGER TRG_PROYECTOS_BU
BEFORE UPDATE ON CRM_PROYECTOS FOR EACH ROW
BEGIN
  :NEW.FECHA_UPDATE := SYSDATE;
END TRG_PROYECTOS_BU;
/

COMMENT ON TABLE CRM_PROYECTOS IS 'Proyectos vinculados a oportunidades cerradas GANADAS';