-- ============================================================
-- CRM EXTRUCOL - CLIENTES DDL
-- ============================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CRM_CLIENTES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CRM_CLIENTES_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE SEQUENCE CRM_CLIENTES_SEQ START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE TABLE CRM_CLIENTES (
  ID              NUMBER         NOT NULL,
  NOMBRE          VARCHAR2(200)  NOT NULL,
  EMPRESA         VARCHAR2(200)  NOT NULL,
  SECTOR          VARCHAR2(100),
  EMAIL           VARCHAR2(200),
  TELEFONO        VARCHAR2(50),
  CIUDAD_ID       NUMBER,
  DIRECCION       VARCHAR2(300),
  NOTAS           CLOB,
  EJECUTIVO_ID    NUMBER         NOT NULL,
  ACTIVO          NUMBER(1)      DEFAULT 1 CHECK (ACTIVO IN (0,1)),
  FECHA_CREACION  DATE           DEFAULT SYSDATE,
  FECHA_UPDATE    DATE           DEFAULT SYSDATE,
  CONSTRAINT CRM_CLIENTES_PK PRIMARY KEY (ID),
  CONSTRAINT CRM_CLIENTES_FK_EJEC FOREIGN KEY (EJECUTIVO_ID) REFERENCES CRM_USUARIOS(ID),
  CONSTRAINT CRM_CLIENTES_FK_CIUDAD FOREIGN KEY (CIUDAD_ID) REFERENCES CRM_CIUDADES(ID)
);

CREATE INDEX CRM_CLIENTES_EJEC_IDX  ON CRM_CLIENTES(EJECUTIVO_ID);
CREATE INDEX CRM_CLIENTES_CIUD_IDX  ON CRM_CLIENTES(CIUDAD_ID);
CREATE INDEX CRM_CLIENTES_SECTOR_IDX ON CRM_CLIENTES(SECTOR);
CREATE INDEX CRM_CLIENTES_EMPRESA_IDX ON CRM_CLIENTES(EMPRESA);

CREATE OR REPLACE TRIGGER TRG_CLIENTES_BI
BEFORE INSERT ON CRM_CLIENTES FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN :NEW.ID := CRM_CLIENTES_SEQ.NEXTVAL; END IF;
END TRG_CLIENTES_BI;
/

CREATE OR REPLACE TRIGGER TRG_CLIENTES_BU
BEFORE UPDATE ON CRM_CLIENTES FOR EACH ROW
BEGIN
  :NEW.FECHA_UPDATE := SYSDATE;
END TRG_CLIENTES_BU;
/

COMMENT ON TABLE CRM_CLIENTES IS 'Empresas y contactos del CRM';