-- ============================================================
-- CRM EXTRUCOL - METAS DDL
-- Período: YYYY-MM
-- Estados: ACTIVA, CUMPLIDA, VENCIDA
-- ============================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CRM_METAS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CRM_METAS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE SEQUENCE CRM_METAS_SEQ START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE TABLE CRM_METAS (
  ID            NUMBER         NOT NULL,
  EJECUTIVO_ID  NUMBER        NOT NULL,
  PERIODO       VARCHAR2(7)   NOT NULL,
  TIPO_META     VARCHAR2(20)  NOT NULL CHECK (TIPO_META IN ('NUMERO','VALOR')),
  META_VALOR    NUMBER(15,2) NOT NULL,
  META_ALCANZADA NUMBER(15,2) DEFAULT 0,
  ESTADO        VARCHAR2(15)  DEFAULT 'ACTIVA' CHECK (ESTADO IN ('ACTIVA','CUMPLIDA','VENCIDA')),
  ACTIVO        NUMBER(1)     DEFAULT 1 CHECK (ACTIVO IN (0,1)),
  FECHA_CREACION DATE         DEFAULT SYSDATE,
  CONSTRAINT CRM_METAS_PK PRIMARY KEY (ID),
  CONSTRAINT CRM_METAS_FK_EJEC FOREIGN KEY (EJECUTIVO_ID) REFERENCES CRM_USUARIOS(ID)
);

CREATE INDEX CRM_METAS_EJEC_IDX   ON CRM_METAS(EJECUTIVO_ID);
CREATE INDEX CRM_METAS_PERIODO_IDX ON CRM_METAS(PERIODO);
CREATE INDEX CRM_METAS_ESTADO_IDX ON CRM_METAS(ESTADO);

CREATE OR REPLACE TRIGGER TRG_METAS_BI
BEFORE INSERT ON CRM_METAS FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN :NEW.ID := CRM_METAS_SEQ.NEXTVAL; END IF;
END TRG_METAS_BI;
/

COMMENT ON TABLE CRM_METAS IS 'Metas mensuales por ejecutivo';

-- ============================================================
-- CRM EXTRUCOL - METAS SEED DATA
-- Metas para 2026
-- ============================================================
INSERT INTO CRM_METAS (ID, EJECUTIVO_ID, PERIODO, TIPO_META, META_VALOR, META_ALCANZADA, ESTADO) VALUES
(1,  3, '2026-01', 'NUMERO', 5,  7, 'CUMPLIDA'),
(2,  4, '2026-01', 'NUMERO', 4,  3, 'VENCIDA'),
(3,  3, '2026-02', 'NUMERO', 5,  6, 'CUMPLIDA'),
(4,  4, '2026-02', 'NUMERO', 4,  5, 'CUMPLIDA'),
(5,  3, '2026-03', 'NUMERO', 5,  4, 'VENCIDA'),
(6,  4, '2026-03', 'NUMERO', 4,  5, 'CUMPLIDA'),
(7,  3, '2026-04', 'NUMERO', 5,  3, 'ACTIVA'),
(8,  4, '2026-04', 'NUMERO', 4,  2, 'ACTIVA'),
(9,  3, '2026-05', 'NUMERO', 5,  0, 'ACTIVA'),
(10, 4, '2026-05', 'NUMERO', 4,  0, 'ACTIVA'),
(11, 3, '2026-06', 'NUMERO', 5,  0, 'ACTIVA'),
(12, 4, '2026-06', 'NUMERO', 4,  0, 'ACTIVA');
COMMIT;