-- ============================================================
-- CRM EXTRUCOL - REPORTES DDL + PROCESOS
-- ============================================================

BEGIN EXECUTE IMMEDIATE 'DROP TABLE CRM_REPORTES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CRM_REPORTES_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE SEQUENCE CRM_REPORTES_SEQ START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE TABLE CRM_REPORTES (
  ID            NUMBER         NOT NULL,
  TIPO          VARCHAR2(30)   NOT NULL,
  TITULO        VARCHAR2(200)  NOT NULL,
  PARAMETROS    CLOB,
  GENERADO_POR  NUMBER         NOT NULL,
  FECHA_GENERA  DATE           DEFAULT SYSDATE,
  ACTIVO        NUMBER(1)      DEFAULT 1 CHECK (ACTIVO IN (0,1)),
  CONSTRAINT CRM_REPORTES_PK PRIMARY KEY (ID),
  CONSTRAINT CRM_REPORTES_FK_USU FOREIGN KEY (GENERADO_POR) REFERENCES CRM_USUARIOS(ID)
);

CREATE OR REPLACE TRIGGER TRG_REPORTES_BI
BEFORE INSERT ON CRM_REPORTES FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN :NEW.ID := CRM_REPORTES_SEQ.NEXTVAL; END IF;
END TRG_REPORTES_BI;
/

-- REPORTES_LIST
DECLARE l_cur SYS_REFCURSOR;
BEGIN
  OPEN l_cur FOR
    SELECT r.id, r.tipo, r.titulo, r.parametros, r.generado_por, u.nombre AS generado_por_nombre,
           r.fecha_genera
      FROM crm_reportes r JOIN crm_usuarios u ON u.id = r.generado_por
     WHERE r.activo = 1 ORDER BY r.fecha_genera DESC;
  APEX_JSON.OPEN_OBJECT; APEX_JSON.WRITE('data', l_cur); APEX_JSON.CLOSE_OBJECT;
END;

-- REPORTES_GENERAR
DECLARE l_id NUMBER;
BEGIN
  INSERT INTO crm_reportes (tipo, titulo, parametros, generado_por)
  VALUES (
    APEX_APPLICATION.G_X01,
    'Reporte generado el ' || TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI'),
    '{"inicio":"' || APEX_APPLICATION.G_X02 || '","fin":"' || APEX_APPLICATION.G_X03 || '"}',
    3
  )
  RETURNING id INTO l_id;
  APEX_JSON.OPEN_OBJECT; APEX_JSON.WRITE('id', l_id); APEX_JSON.WRITE('success', TRUE); APEX_JSON.CLOSE_OBJECT;
EXCEPTION WHEN OTHERS THEN
  APEX_JSON.OPEN_OBJECT; APEX_JSON.WRITE('success', FALSE); APEX_JSON.WRITE('error', SQLERRM); APEX_JSON.CLOSE_OBJECT;
END;