-- ============================================================
-- CRM EXTRUCOL - BASE DATA DDL
-- Catálogo de ciudades colombianas
-- ============================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CRM_CIUDADES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CRM_CIUDADES_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE SEQUENCE CRM_CIUDADES_SEQ START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE TABLE CRM_CIUDADES (
  ID              NUMBER         NOT NULL,
  NOMBRE          VARCHAR2(200)  NOT NULL,
  DEPARTAMENTO    VARCHAR2(200)  NOT NULL,
  PAIS            VARCHAR2(100)  DEFAULT 'Colombia' NOT NULL,
  ACTIVO          NUMBER(1)      DEFAULT 1 CHECK (ACTIVO IN (0,1)),
  FECHA_CREACION  DATE           DEFAULT SYSDATE,
  CONSTRAINT CRM_CIUDADES_PK PRIMARY KEY (ID)
);

CREATE OR REPLACE TRIGGER TRG_CIUDADES_BI
BEFORE INSERT ON CRM_CIUDADES FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    :NEW.ID := CRM_CIUDADES_SEQ.NEXTVAL;
  END IF;
END TRG_CIUDADES_BI;
/

CREATE OR REPLACE TRIGGER TRG_CIUDADES_BU
BEFORE UPDATE ON CRM_CIUDADES FOR EACH ROW
BEGIN
  NULL;
END TRG_CIUDADES_BU;
/

COMMENT ON TABLE CRM_CIUDADES IS 'Catálogo de ciudades y departamentos de Colombia';
COMMENT ON COLUMN CRM_CIUDADES.NOMBRE      IS 'Nombre de la ciudad';
COMMENT ON COLUMN CRM_CIUDADES.DEPARTAMENTO IS 'Nombre del departamento';