-- ============================================================
-- CRM EXTRUCOL - MONITOREO DDL
-- GPS de ejecutivos
-- ============================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CRM_UBICACIONES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CRM_UBICACIONES_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE SEQUENCE CRM_UBICACIONES_SEQ START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE TABLE CRM_UBICACIONES (
  ID            NUMBER         NOT NULL,
  USUARIO_ID    NUMBER         NOT NULL,
  LATITUD       NUMBER(10,6)  NOT NULL,
  LONGITUD      NUMBER(10,6)  NOT NULL,
  PRECISION     NUMBER(6,2),
  FECHA_REGISTRO DATE         DEFAULT SYSDATE,
  ACTIVO        NUMBER(1)      DEFAULT 1 CHECK (ACTIVO IN (0,1)),
  CONSTRAINT CRM_UBICACIONES_PK PRIMARY KEY (ID),
  CONSTRAINT CRM_UBICACIONES_FK_USU FOREIGN KEY (USUARIO_ID) REFERENCES CRM_USUARIOS(ID)
);

CREATE INDEX CRM_UBICACIONES_USU_IDX   ON CRM_UBICACIONES(USUARIO_ID);
CREATE INDEX CRM_UBICACIONES_FECHA_IDX ON CRM_UBICACIONES(FECHA_REGISTRO);

CREATE OR REPLACE TRIGGER TRG_UBICACIONES_BI
BEFORE INSERT ON CRM_UBICACIONES FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN :NEW.ID := CRM_UBICACIONES_SEQ.NEXTVAL; END IF;
END TRG_UBICACIONES_BI;
/

COMMENT ON TABLE CRM_UBICACIONES IS 'Ubicaciones GPS de ejecutivos';

-- ============================================================
-- CRM EXTRUCOL - MONITOREO SEED DATA
-- ============================================================
INSERT INTO CRM_UBICACIONES (ID, USUARIO_ID, LATITUD, LONGITUD, PRECISION, FECHA_REGISTRO) VALUES
(1, 3, 7.1139,  -73.1126, 10.5, SYSDATE - INTERVAL '2' HOUR),
(2, 4, 6.2476,  -75.5658, 8.2,  SYSDATE - INTERVAL '1' HOUR),
(3, 5, 10.9634, -74.7963, 15.0, SYSDATE - INTERVAL '3' HOUR);
COMMIT;