-- ============================================================
-- CRM EXTRUCOL - ACTIVIDADES DDL
-- Tipos: LLAMADA, REUNION, VISITA, CORREO
-- ============================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CRM_ACTIVIDADES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CRM_ACTIVIDADES_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE SEQUENCE CRM_ACTIVIDADES_SEQ START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE TABLE CRM_ACTIVIDADES (
  ID                NUMBER         NOT NULL,
  TIPO              VARCHAR2(20)   NOT NULL CHECK (TIPO IN ('LLAMADA','REUNION','VISITA','CORREO')),
  DESCRIPCION       CLOB,
  RESULTADO         CLOB,
  VIRTUAL           NUMBER(1)      DEFAULT 0 CHECK (VIRTUAL IN (0,1)),
  FECHA_ACTIVIDAD   DATE,
  FECHA_REGISTRO    DATE          DEFAULT SYSDATE,
  OPORTUNIDAD_ID    NUMBER,
  EJECUTIVO_ID      NUMBER        NOT NULL,
  LATITUD           NUMBER(10,6),
  LONGITUD          NUMBER(10,6),
  ACTIVO            NUMBER(1)     DEFAULT 1 CHECK (ACTIVO IN (0,1)),
  FECHA_CREACION    DATE          DEFAULT SYSDATE,
  FECHA_UPDATE      DATE          DEFAULT SYSDATE,
  CONSTRAINT CRM_ACTIVIDADES_PK PRIMARY KEY (ID),
  CONSTRAINT CRM_ACTIVIDADES_FK_OPOR FOREIGN KEY (OPORTUNIDAD_ID) REFERENCES CRM_OPORTUNIDADES(ID),
  CONSTRAINT CRM_ACTIVIDADES_FK_EJEC FOREIGN KEY (EJECUTIVO_ID) REFERENCES CRM_USUARIOS(ID)
);

CREATE INDEX CRM_ACTIVIDADES_OPOR_IDX   ON CRM_ACTIVIDADES(OPORTUNIDAD_ID);
CREATE INDEX CRM_ACTIVIDADES_EJEC_IDX   ON CRM_ACTIVIDADES(EJECUTIVO_ID);
CREATE INDEX CRM_ACTIVIDADES_FECHA_IDX ON CRM_ACTIVIDADES(FECHA_ACTIVIDAD);
CREATE INDEX CRM_ACTIVIDADES_TIPO_IDX  ON CRM_ACTIVIDADES(TIPO);

CREATE OR REPLACE TRIGGER TRG_ACTIVIDADES_BI
BEFORE INSERT ON CRM_ACTIVIDADES FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN :NEW.ID := CRM_ACTIVIDADES_SEQ.NEXTVAL; END IF;
END TRG_ACTIVIDADES_BI;
/

CREATE OR REPLACE TRIGGER TRG_ACTIVIDADES_BU
BEFORE UPDATE ON CRM_ACTIVIDADES FOR EACH ROW
BEGIN
  :NEW.FECHA_UPDATE := SYSDATE;
END TRG_ACTIVIDADES_BU;
/

COMMENT ON TABLE CRM_ACTIVIDADES IS 'Actividades comerciales vinculadas a oportunidades';