-- ============================================================
-- CRM EXTRUCOL - USUARIOS DDL
-- Ejecutivos, Coordinadores, Directores, Admin
-- ============================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CRM_USUARIOS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CRM_USUARIOS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE SEQUENCE CRM_USUARIOS_SEQ START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE TABLE CRM_USUARIOS (
  ID              NUMBER         NOT NULL,
  NOMBRE          VARCHAR2(200)  NOT NULL,
  EMAIL           VARCHAR2(200)  NOT NULL UNIQUE,
  ROL             VARCHAR2(30)   NOT NULL CHECK (ROL IN ('ADMIN','DIRECTOR','COORDINADOR','EJECUTIVO')),
  TELEFONO        VARCHAR2(50),
  CIUDAD_ID       NUMBER,
  ACTIVO          NUMBER(1)      DEFAULT 1 CHECK (ACTIVO IN (0,1)),
  FECHA_CREACION  DATE           DEFAULT SYSDATE,
  FECHA_UPDATE    DATE           DEFAULT SYSDATE,
  CONSTRAINT CRM_USUARIOS_PK PRIMARY KEY (ID),
  CONSTRAINT CRM_USUARIOS_FK_CIUDAD FOREIGN KEY (CIUDAD_ID) REFERENCES CRM_CIUDADES(ID)
);

CREATE INDEX CRM_USUARIOS_EMAIL_IDX ON CRM_USUARIOS(EMAIL);
CREATE INDEX CRM_USUARIOS_ROL_IDX   ON CRM_USUARIOS(ROL);
CREATE INDEX CRM_USUARIOS_ACTIVO_IDX ON CRM_USUARIOS(ACTIVO);

CREATE OR REPLACE TRIGGER TRG_USUARIOS_BI
BEFORE INSERT ON CRM_USUARIOS FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    :NEW.ID := CRM_USUARIOS_SEQ.NEXTVAL;
  END IF;
END TRG_USUARIOS_BI;
/

CREATE OR REPLACE TRIGGER TRG_USUARIOS_BU
BEFORE UPDATE ON CRM_USUARIOS FOR EACH ROW
BEGIN
  :NEW.FECHA_UPDATE := SYSDATE;
END TRG_USUARIOS_BU;
/

COMMENT ON TABLE CRM_USUARIOS IS 'Usuarios del CRM: ejecutivos, coordinadores, directores y administradores';
COMMENT ON COLUMN CRM_USUARIOS.ROL IS 'ADMIN|DIRECTOR|COORDINADOR|EJECUTIVO';