-- ============================================================
-- CRM EXTRUCOL - LEADS DDL
-- Prospectos en calificación
-- Estados: NUEVO, CONTACTADO, CALIFICADO, DESCARTADO, CONVERTIDO
-- ============================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CRM_LEADS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CRM_LEADS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE SEQUENCE CRM_LEADS_SEQ START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE TABLE CRM_LEADS (
  ID              NUMBER         NOT NULL,
  NOMBRE          VARCHAR2(200)  NOT NULL,
  EMPRESA        VARCHAR2(200),
  EMAIL           VARCHAR2(200),
  TELEFONO        VARCHAR2(50),
  ORIGEN          VARCHAR2(100),
  SECTOR          VARCHAR2(100),
  CIUDAD_ID       NUMBER,
  DESCRIPCION     CLOB,
  ESTADO          VARCHAR2(30)   DEFAULT 'NUEVO'
                  CHECK (ESTADO IN ('NUEVO','CONTACTADO','CALIFICADO','DESCARTADO','CONVERTIDO')),
  EJECUTIVO_ID    NUMBER         NOT NULL,
  ACTIVO          NUMBER(1)      DEFAULT 1 CHECK (ACTIVO IN (0,1)),
  FECHA_CREACION  DATE           DEFAULT SYSDATE,
  FECHA_UPDATE    DATE           DEFAULT SYSDATE,
  CONSTRAINT CRM_LEADS_PK PRIMARY KEY (ID),
  CONSTRAINT CRM_LEADS_FK_EJEC FOREIGN KEY (EJECUTIVO_ID) REFERENCES CRM_USUARIOS(ID),
  CONSTRAINT CRM_LEADS_FK_CIUD  FOREIGN KEY (CIUDAD_ID)    REFERENCES CRM_CIUDADES(ID)
);

CREATE INDEX CRM_LEADS_ESTADO_IDX ON CRM_LEADS(ESTADO);
CREATE INDEX CRM_LEADS_EJEC_IDX  ON CRM_LEADS(EJECUTIVO_ID);
CREATE INDEX CRM_LEADS_ORIGEN_IDX ON CRM_LEADS(ORIGEN);

CREATE OR REPLACE TRIGGER TRG_LEADS_BI
BEFORE INSERT ON CRM_LEADS FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN :NEW.ID := CRM_LEADS_SEQ.NEXTVAL; END IF;
END TRG_LEADS_BI;
/

CREATE OR REPLACE TRIGGER TRG_LEADS_BU
BEFORE UPDATE ON CRM_LEADS FOR EACH ROW
BEGIN
  :NEW.FECHA_UPDATE := SYSDATE;
END TRG_LEADS_BU;
/

COMMENT ON TABLE CRM_LEADS IS 'Prospectos en calificación del pipeline comercial';
COMMENT ON COLUMN CRM_LEADS.ESTADO IS 'NUEVO|CONTACTADO|CALIFICADO|DESCARTADO|CONVERTIDO';