-- ============================================================
-- CRM EXTRUCOL - OPORTUNIDADES DDL
-- Estados: PROSPECTO, CALIFICACION, PROPUESTA, NEGOCIACION, GANADA, PERDIDA
-- ============================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CRM_OPORTUNIDADES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CRM_OPORTUNIDADES_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE SEQUENCE CRM_OPORTUNIDADES_SEQ START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE TABLE CRM_OPORTUNIDADES (
  ID                NUMBER         NOT NULL,
  NOMBRE            VARCHAR2(300)  NOT NULL,
  DESCRIPCION       CLOB,
  TIPO              VARCHAR2(30)   DEFAULT 'VENTA'
                    CHECK (TIPO IN ('COTIZACION','VENTA','ACOMPANAMIENTO','PROYECTO')),
  ESTADO            VARCHAR2(30)   DEFAULT 'PROSPECTO'
                    CHECK (ESTADO IN ('PROSPECTO','CALIFICACION','PROPUESTA','NEGOCIACION','GANADA','PERDIDA')),
  VALOR_ESTIMADO    NUMBER(15,2) DEFAULT 0,
  FECHA_CIERRE      DATE,
  FECHA_ESTADO       DATE           DEFAULT SYSDATE,
  CLIENTE_ID        NUMBER,
  EJECUTIVO_ID      NUMBER         NOT NULL,
  MOTIVO_CIERRE     VARCHAR2(500),
  ACTIVO            NUMBER(1)      DEFAULT 1 CHECK (ACTIVO IN (0,1)),
  FECHA_CREACION    DATE           DEFAULT SYSDATE,
  FECHA_UPDATE      DATE           DEFAULT SYSDATE,
  CONSTRAINT CRM_OPORTUNIDADES_PK PRIMARY KEY (ID),
  CONSTRAINT CRM_OPORTUNIDADES_FK_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CRM_CLIENTES(ID),
  CONSTRAINT CRM_OPORTUNIDADES_FK_EJEC FOREIGN KEY (EJECUTIVO_ID) REFERENCES CRM_USUARIOS(ID)
);

CREATE INDEX CRM_OPORTUNIDADES_ESTADO_IDX  ON CRM_OPORTUNIDADES(ESTADO);
CREATE INDEX CRM_OPORTUNIDADES_EJEC_IDX   ON CRM_OPORTUNIDADES(EJECUTIVO_ID);
CREATE INDEX CRM_OPORTUNIDADES_CLIENTE_IDX ON CRM_OPORTUNIDADES(CLIENTE_ID);
CREATE INDEX CRM_OPORTUNIDADES_TIPO_IDX   ON CRM_OPORTUNIDADES(TIPO);

CREATE OR REPLACE TRIGGER TRG_OPORTUNIDADES_BI
BEFORE INSERT ON CRM_OPORTUNIDADES FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN :NEW.ID := CRM_OPORTUNIDADES_SEQ.NEXTVAL; END IF;
END TRG_OPORTUNIDADES_BI;
/

CREATE OR REPLACE TRIGGER TRG_OPORTUNIDADES_BU
BEFORE UPDATE ON CRM_OPORTUNIDADES FOR EACH ROW
BEGIN
  :NEW.FECHA_UPDATE := SYSDATE;
  IF :NEW.ESTADO != :OLD.ESTADO THEN
    :NEW.FECHA_ESTADO := SYSDATE;
  END IF;
END TRG_OPORTUNIDADES_BU;
/

COMMENT ON TABLE CRM_OPORTUNIDADES IS 'Oportunidades del pipeline comercial';
COMMENT ON COLUMN CRM_OPORTUNIDADES.TIPO IS 'COTIZACION|VENTA|ACOMPANAMIENTO|PROYECTO';
COMMENT ON COLUMN CRM_OPORTUNIDADES.ESTADO IS 'PROSPECTO|CALIFICACION|PROPUESTA|NEGOCIACION|GANADA|PERDIDA';